from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from app import db

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    role = db.Column(db.String(20), nullable=False, default='employee')  # admin, hr, manager, employee
    employee_id = db.Column(db.String(50), unique=True, nullable=False)
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    last_login = db.Column(db.DateTime)
    
    # Relationship
    employee = db.relationship('Employee', backref='user', uselist=False, cascade='all, delete-orphan')
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def __repr__(self):
        return f'<User {self.username}>'

class Employee(db.Model):
    __tablename__ = 'employees'
    
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.String(50), unique=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    middle_name = db.Column(db.String(100))
    position = db.Column(db.String(100))
    department_id = db.Column(db.Integer, db.ForeignKey('departments.id'))
    status_of_appointment = db.Column(db.String(50))  # Permanent, Casual, Contractual, etc.
    nature_of_appointment = db.Column(db.String(50))  # Original, Reemployment, Transfer, etc.
    # NOTE: UI label is "Appointment Date". We keep the underlying DB column name
    # as "hire_date" for backward compatibility (no immediate ALTER TABLE needed).
    appointment_date = db.Column('hire_date', db.Date)
    phone = db.Column(db.String(20))
    mobile_no = db.Column(db.String(20))
    # Address fields matching PDS structure
    residential_house_no = db.Column(db.String(100))
    residential_street = db.Column(db.String(200))
    residential_subdivision = db.Column(db.String(200))
    residential_barangay = db.Column(db.String(100))
    residential_city = db.Column(db.String(100))
    residential_province = db.Column(db.String(100))
    residential_zip_code = db.Column(db.String(10))
    address = db.Column(db.Text)  # Keep for backward compatibility
    status = db.Column(db.String(20), default='active')  # active, on_leave, terminated
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    department = db.relationship('Department', foreign_keys=[department_id], backref='employees')
    attendance_records = db.relationship('Attendance', backref='employee', lazy='dynamic')
    leave_requests = db.relationship('LeaveRequest', backref='employee', lazy='dynamic')
    
    @property
    def full_name(self):
        if self.middle_name:
            return f"{self.first_name} {self.middle_name} {self.last_name}"
        return f"{self.first_name} {self.last_name}"
    
    def __repr__(self):
        return f'<Employee {self.employee_id}: {self.full_name}>'

    # Backward-compatible alias (older code/templates might reference hire_date)
    @property
    def hire_date(self):
        return self.appointment_date

    @hire_date.setter
    def hire_date(self, value):
        self.appointment_date = value

class Department(db.Model):
    __tablename__ = 'departments'
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.Text)
    manager_id = db.Column(db.Integer, db.ForeignKey('employees.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    manager = db.relationship('Employee', foreign_keys=[manager_id], backref='managed_departments')
    
    def __repr__(self):
        return f'<Department {self.name}>'

class SalaryGrade(db.Model):
    __tablename__ = 'salary_grade'
    
    id = db.Column(db.Integer, primary_key=True)
    sg = db.Column(db.Integer, nullable=True)
    sg_agency = db.Column(db.String(100), nullable=True)
    sg_tranche = db.Column(db.String(50), nullable=True)
    sg_step_1 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_2 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_3 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_4 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_5 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_6 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_7 = db.Column(db.Numeric(12, 2), nullable=True)
    sg_step_8 = db.Column(db.Numeric(12, 2), nullable=True)

    def __repr__(self):
        return f'<SalaryGrade sg={self.sg} tranche={self.sg_tranche} agency={self.sg_agency}>'

class Position(db.Model):
    __tablename__ = 'positions'
    
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False, unique=True)

    def __repr__(self):
        return f'<Position {self.title}>'

class Attendance(db.Model):
    __tablename__ = 'attendance'
    
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'), nullable=False)
    date = db.Column(db.Date, nullable=False)
    time_in = db.Column(db.Time)
    time_out = db.Column(db.Time)
    status = db.Column(db.String(20), default='present')  # present, absent, late, on_leave
    notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f'<Attendance {self.employee_id} - {self.date}>'

class LeaveRequest(db.Model):
    __tablename__ = 'leave_requests'
    
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'), nullable=False)
    leave_type = db.Column(db.String(50), nullable=False)  # vacation, sick, personal, etc.
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)
    reason = db.Column(db.Text)
    status = db.Column(db.String(20), default='pending')  # pending, approved, rejected
    approved_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    approved_at = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    approver = db.relationship('User', foreign_keys=[approved_by])
    
    def __repr__(self):
        return f'<LeaveRequest {self.id} - {self.status}>'

class EmployeePDS(db.Model):
    __tablename__ = 'employee_pds'
    
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey('employees.id'), nullable=False, unique=True)
    
    # Personal Information Section I
    surname = db.Column(db.String(100))
    first_name = db.Column(db.String(100))
    middle_name = db.Column(db.String(100))
    name_extension = db.Column(db.String(10))  # JR., SR, etc.
    date_of_birth = db.Column(db.Date)
    place_of_birth = db.Column(db.String(200))
    sex_at_birth = db.Column(db.String(10))  # Male, Female
    civil_status = db.Column(db.String(20))  # Single, Married, Widowed, Separated, Other
    civil_status_other = db.Column(db.String(50))
    height = db.Column(db.String(20))  # in meters
    weight = db.Column(db.String(20))  # in kg
    blood_type = db.Column(db.String(10))
    umid_id = db.Column(db.String(50))
    pagibig_id = db.Column(db.String(50))
    philhealth_no = db.Column(db.String(50))
    philsys_number = db.Column(db.String(50))  # PSN
    tin_no = db.Column(db.String(50))
    agency_employee_no = db.Column(db.String(50))
    
    # Citizenship
    citizenship = db.Column(db.String(20))  # Filipino, Dual Citizenship
    dual_citizenship_type = db.Column(db.String(20))  # by birth, by naturalization
    dual_citizenship_country = db.Column(db.String(100))
    
    # Residential Address
    residential_house_no = db.Column(db.String(100))
    residential_street = db.Column(db.String(200))
    residential_subdivision = db.Column(db.String(200))
    residential_barangay = db.Column(db.String(100))
    residential_city = db.Column(db.String(100))
    residential_province = db.Column(db.String(100))
    residential_zip_code = db.Column(db.String(10))
    
    # Permanent Address
    permanent_house_no = db.Column(db.String(100))
    permanent_street = db.Column(db.String(200))
    permanent_subdivision = db.Column(db.String(200))
    permanent_barangay = db.Column(db.String(100))
    permanent_city = db.Column(db.String(100))
    permanent_province = db.Column(db.String(100))
    permanent_zip_code = db.Column(db.String(10))
    
    # Contact Information
    telephone_no = db.Column(db.String(20))
    mobile_no = db.Column(db.String(20))
    email_address = db.Column(db.String(200))
    
    # Family Background Section II
    # Section 22: Spouse's Information
    spouse_surname = db.Column(db.String(100))
    spouse_first_name = db.Column(db.String(100))
    spouse_middle_name = db.Column(db.String(100))
    spouse_name_extension = db.Column(db.String(10))  # JR., SR, etc.
    spouse_occupation = db.Column(db.String(200))
    spouse_employer = db.Column(db.String(200))
    spouse_business_address = db.Column(db.String(500))
    spouse_telephone_no = db.Column(db.String(20))
    
    # Section 23: Children's Information (up to 20 children)
    child1_name = db.Column(db.String(200))
    child1_date_of_birth = db.Column(db.Date)
    child2_name = db.Column(db.String(200))
    child2_date_of_birth = db.Column(db.Date)
    child3_name = db.Column(db.String(200))
    child3_date_of_birth = db.Column(db.Date)
    child4_name = db.Column(db.String(200))
    child4_date_of_birth = db.Column(db.Date)
    child5_name = db.Column(db.String(200))
    child5_date_of_birth = db.Column(db.Date)
    child6_name = db.Column(db.String(200))
    child6_date_of_birth = db.Column(db.Date)
    child7_name = db.Column(db.String(200))
    child7_date_of_birth = db.Column(db.Date)
    child8_name = db.Column(db.String(200))
    child8_date_of_birth = db.Column(db.Date)
    child9_name = db.Column(db.String(200))
    child9_date_of_birth = db.Column(db.Date)
    child10_name = db.Column(db.String(200))
    child10_date_of_birth = db.Column(db.Date)
    child11_name = db.Column(db.String(200))
    child11_date_of_birth = db.Column(db.Date)
    child12_name = db.Column(db.String(200))
    child12_date_of_birth = db.Column(db.Date)
    child13_name = db.Column(db.String(200))
    child13_date_of_birth = db.Column(db.Date)
    child14_name = db.Column(db.String(200))
    child14_date_of_birth = db.Column(db.Date)
    child15_name = db.Column(db.String(200))
    child15_date_of_birth = db.Column(db.Date)
    child16_name = db.Column(db.String(200))
    child16_date_of_birth = db.Column(db.Date)
    child17_name = db.Column(db.String(200))
    child17_date_of_birth = db.Column(db.Date)
    child18_name = db.Column(db.String(200))
    child18_date_of_birth = db.Column(db.Date)
    child19_name = db.Column(db.String(200))
    child19_date_of_birth = db.Column(db.Date)
    child20_name = db.Column(db.String(200))
    child20_date_of_birth = db.Column(db.Date)
    
    # Section 24: Father's Information
    father_surname = db.Column(db.String(100))
    father_first_name = db.Column(db.String(100))
    father_middle_name = db.Column(db.String(100))
    father_name_extension = db.Column(db.String(10))  # JR., SR, etc.
    
    # Section 25: Mother's Maiden Name
    mother_surname = db.Column(db.String(100))
    mother_first_name = db.Column(db.String(100))
    mother_middle_name = db.Column(db.String(100))
    
    # Section III: Educational Background
    # Each level can have multiple entries (up to 5 entries per level)
    # Elementary Education (entries 1-5)
    elementary1_school = db.Column(db.String(500))
    elementary1_degree = db.Column(db.String(200))
    elementary1_from = db.Column(db.String(50))
    elementary1_to = db.Column(db.String(50))
    elementary1_highest_level = db.Column(db.String(200))
    elementary1_year_graduated = db.Column(db.String(10))
    elementary1_honors = db.Column(db.String(500))
    elementary2_school = db.Column(db.String(500))
    elementary2_degree = db.Column(db.String(200))
    elementary2_from = db.Column(db.String(50))
    elementary2_to = db.Column(db.String(50))
    elementary2_highest_level = db.Column(db.String(200))
    elementary2_year_graduated = db.Column(db.String(10))
    elementary2_honors = db.Column(db.String(500))
    elementary3_school = db.Column(db.String(500))
    elementary3_degree = db.Column(db.String(200))
    elementary3_from = db.Column(db.String(50))
    elementary3_to = db.Column(db.String(50))
    elementary3_highest_level = db.Column(db.String(200))
    elementary3_year_graduated = db.Column(db.String(10))
    elementary3_honors = db.Column(db.String(500))
    elementary4_school = db.Column(db.String(500))
    elementary4_degree = db.Column(db.String(200))
    elementary4_from = db.Column(db.String(50))
    elementary4_to = db.Column(db.String(50))
    elementary4_highest_level = db.Column(db.String(200))
    elementary4_year_graduated = db.Column(db.String(10))
    elementary4_honors = db.Column(db.String(500))
    elementary5_school = db.Column(db.String(500))
    elementary5_degree = db.Column(db.String(200))
    elementary5_from = db.Column(db.String(50))
    elementary5_to = db.Column(db.String(50))
    elementary5_highest_level = db.Column(db.String(200))
    elementary5_year_graduated = db.Column(db.String(10))
    elementary5_honors = db.Column(db.String(500))
    
    # Secondary Education (entries 1-5)
    secondary1_school = db.Column(db.String(500))
    secondary1_degree = db.Column(db.String(200))
    secondary1_from = db.Column(db.String(50))
    secondary1_to = db.Column(db.String(50))
    secondary1_highest_level = db.Column(db.String(200))
    secondary1_year_graduated = db.Column(db.String(10))
    secondary1_honors = db.Column(db.String(500))
    secondary2_school = db.Column(db.String(500))
    secondary2_degree = db.Column(db.String(200))
    secondary2_from = db.Column(db.String(50))
    secondary2_to = db.Column(db.String(50))
    secondary2_highest_level = db.Column(db.String(200))
    secondary2_year_graduated = db.Column(db.String(10))
    secondary2_honors = db.Column(db.String(500))
    secondary3_school = db.Column(db.String(500))
    secondary3_degree = db.Column(db.String(200))
    secondary3_from = db.Column(db.String(50))
    secondary3_to = db.Column(db.String(50))
    secondary3_highest_level = db.Column(db.String(200))
    secondary3_year_graduated = db.Column(db.String(10))
    secondary3_honors = db.Column(db.String(500))
    secondary4_school = db.Column(db.String(500))
    secondary4_degree = db.Column(db.String(200))
    secondary4_from = db.Column(db.String(50))
    secondary4_to = db.Column(db.String(50))
    secondary4_highest_level = db.Column(db.String(200))
    secondary4_year_graduated = db.Column(db.String(10))
    secondary4_honors = db.Column(db.String(500))
    secondary5_school = db.Column(db.String(500))
    secondary5_degree = db.Column(db.String(200))
    secondary5_from = db.Column(db.String(50))
    secondary5_to = db.Column(db.String(50))
    secondary5_highest_level = db.Column(db.String(200))
    secondary5_year_graduated = db.Column(db.String(10))
    secondary5_honors = db.Column(db.String(500))
    
    # Vocational/Trade Course (entries 1-5)
    vocational1_school = db.Column(db.String(500))
    vocational1_degree = db.Column(db.String(200))
    vocational1_from = db.Column(db.String(50))
    vocational1_to = db.Column(db.String(50))
    vocational1_highest_level = db.Column(db.String(200))
    vocational1_year_graduated = db.Column(db.String(10))
    vocational1_honors = db.Column(db.String(500))
    vocational2_school = db.Column(db.String(500))
    vocational2_degree = db.Column(db.String(200))
    vocational2_from = db.Column(db.String(50))
    vocational2_to = db.Column(db.String(50))
    vocational2_highest_level = db.Column(db.String(200))
    vocational2_year_graduated = db.Column(db.String(10))
    vocational2_honors = db.Column(db.String(500))
    vocational3_school = db.Column(db.String(500))
    vocational3_degree = db.Column(db.String(200))
    vocational3_from = db.Column(db.String(50))
    vocational3_to = db.Column(db.String(50))
    vocational3_highest_level = db.Column(db.String(200))
    vocational3_year_graduated = db.Column(db.String(10))
    vocational3_honors = db.Column(db.String(500))
    vocational4_school = db.Column(db.String(500))
    vocational4_degree = db.Column(db.String(200))
    vocational4_from = db.Column(db.String(50))
    vocational4_to = db.Column(db.String(50))
    vocational4_highest_level = db.Column(db.String(200))
    vocational4_year_graduated = db.Column(db.String(10))
    vocational4_honors = db.Column(db.String(500))
    vocational5_school = db.Column(db.String(500))
    vocational5_degree = db.Column(db.String(200))
    vocational5_from = db.Column(db.String(50))
    vocational5_to = db.Column(db.String(50))
    vocational5_highest_level = db.Column(db.String(200))
    vocational5_year_graduated = db.Column(db.String(10))
    vocational5_honors = db.Column(db.String(500))
    
    # College (entries 1-5)
    college1_school = db.Column(db.String(500))
    college1_degree = db.Column(db.String(200))
    college1_from = db.Column(db.String(50))
    college1_to = db.Column(db.String(50))
    college1_highest_level = db.Column(db.String(200))
    college1_year_graduated = db.Column(db.String(10))
    college1_honors = db.Column(db.String(500))
    college2_school = db.Column(db.String(500))
    college2_degree = db.Column(db.String(200))
    college2_from = db.Column(db.String(50))
    college2_to = db.Column(db.String(50))
    college2_highest_level = db.Column(db.String(200))
    college2_year_graduated = db.Column(db.String(10))
    college2_honors = db.Column(db.String(500))
    college3_school = db.Column(db.String(500))
    college3_degree = db.Column(db.String(200))
    college3_from = db.Column(db.String(50))
    college3_to = db.Column(db.String(50))
    college3_highest_level = db.Column(db.String(200))
    college3_year_graduated = db.Column(db.String(10))
    college3_honors = db.Column(db.String(500))
    college4_school = db.Column(db.String(500))
    college4_degree = db.Column(db.String(200))
    college4_from = db.Column(db.String(50))
    college4_to = db.Column(db.String(50))
    college4_highest_level = db.Column(db.String(200))
    college4_year_graduated = db.Column(db.String(10))
    college4_honors = db.Column(db.String(500))
    college5_school = db.Column(db.String(500))
    college5_degree = db.Column(db.String(200))
    college5_from = db.Column(db.String(50))
    college5_to = db.Column(db.String(50))
    college5_highest_level = db.Column(db.String(200))
    college5_year_graduated = db.Column(db.String(10))
    college5_honors = db.Column(db.String(500))
    
    # Graduate Studies (entries 1-5)
    graduate1_school = db.Column(db.String(500))
    graduate1_degree = db.Column(db.String(200))
    graduate1_from = db.Column(db.String(50))
    graduate1_to = db.Column(db.String(50))
    graduate1_highest_level = db.Column(db.String(200))
    graduate1_year_graduated = db.Column(db.String(10))
    graduate1_honors = db.Column(db.String(500))
    graduate2_school = db.Column(db.String(500))
    graduate2_degree = db.Column(db.String(200))
    graduate2_from = db.Column(db.String(50))
    graduate2_to = db.Column(db.String(50))
    graduate2_highest_level = db.Column(db.String(200))
    graduate2_year_graduated = db.Column(db.String(10))
    graduate2_honors = db.Column(db.String(500))
    graduate3_school = db.Column(db.String(500))
    graduate3_degree = db.Column(db.String(200))
    graduate3_from = db.Column(db.String(50))
    graduate3_to = db.Column(db.String(50))
    graduate3_highest_level = db.Column(db.String(200))
    graduate3_year_graduated = db.Column(db.String(10))
    graduate3_honors = db.Column(db.String(500))
    graduate4_school = db.Column(db.String(500))
    graduate4_degree = db.Column(db.String(200))
    graduate4_from = db.Column(db.String(50))
    graduate4_to = db.Column(db.String(50))
    graduate4_highest_level = db.Column(db.String(200))
    graduate4_year_graduated = db.Column(db.String(10))
    graduate4_honors = db.Column(db.String(500))
    graduate5_school = db.Column(db.String(500))
    graduate5_degree = db.Column(db.String(200))
    graduate5_from = db.Column(db.String(50))
    graduate5_to = db.Column(db.String(50))
    graduate5_highest_level = db.Column(db.String(200))
    graduate5_year_graduated = db.Column(db.String(10))
    graduate5_honors = db.Column(db.String(500))
    
    # Section IV: Civil Service Eligibility (up to 10 entries)
    civil_service1_eligibility = db.Column(db.String(500))
    civil_service1_rating = db.Column(db.String(50))
    civil_service1_date = db.Column(db.String(50))
    civil_service1_place = db.Column(db.String(500))
    civil_service1_license_number = db.Column(db.String(100))
    civil_service1_license_valid_until = db.Column(db.String(50))
    civil_service2_eligibility = db.Column(db.String(500))
    civil_service2_rating = db.Column(db.String(50))
    civil_service2_date = db.Column(db.String(50))
    civil_service2_place = db.Column(db.String(500))
    civil_service2_license_number = db.Column(db.String(100))
    civil_service2_license_valid_until = db.Column(db.String(50))
    civil_service3_eligibility = db.Column(db.String(500))
    civil_service3_rating = db.Column(db.String(50))
    civil_service3_date = db.Column(db.String(50))
    civil_service3_place = db.Column(db.String(500))
    civil_service3_license_number = db.Column(db.String(100))
    civil_service3_license_valid_until = db.Column(db.String(50))
    civil_service4_eligibility = db.Column(db.String(500))
    civil_service4_rating = db.Column(db.String(50))
    civil_service4_date = db.Column(db.String(50))
    civil_service4_place = db.Column(db.String(500))
    civil_service4_license_number = db.Column(db.String(100))
    civil_service4_license_valid_until = db.Column(db.String(50))
    civil_service5_eligibility = db.Column(db.String(500))
    civil_service5_rating = db.Column(db.String(50))
    civil_service5_date = db.Column(db.String(50))
    civil_service5_place = db.Column(db.String(500))
    civil_service5_license_number = db.Column(db.String(100))
    civil_service5_license_valid_until = db.Column(db.String(50))
    civil_service6_eligibility = db.Column(db.String(500))
    civil_service6_rating = db.Column(db.String(50))
    civil_service6_date = db.Column(db.String(50))
    civil_service6_place = db.Column(db.String(500))
    civil_service6_license_number = db.Column(db.String(100))
    civil_service6_license_valid_until = db.Column(db.String(50))
    civil_service7_eligibility = db.Column(db.String(500))
    civil_service7_rating = db.Column(db.String(50))
    civil_service7_date = db.Column(db.String(50))
    civil_service7_place = db.Column(db.String(500))
    civil_service7_license_number = db.Column(db.String(100))
    civil_service7_license_valid_until = db.Column(db.String(50))
    civil_service8_eligibility = db.Column(db.String(500))
    civil_service8_rating = db.Column(db.String(50))
    civil_service8_date = db.Column(db.String(50))
    civil_service8_place = db.Column(db.String(500))
    civil_service8_license_number = db.Column(db.String(100))
    civil_service8_license_valid_until = db.Column(db.String(50))
    civil_service9_eligibility = db.Column(db.String(500))
    civil_service9_rating = db.Column(db.String(50))
    civil_service9_date = db.Column(db.String(50))
    civil_service9_place = db.Column(db.String(500))
    civil_service9_license_number = db.Column(db.String(100))
    civil_service9_license_valid_until = db.Column(db.String(50))
    civil_service10_eligibility = db.Column(db.String(500))
    civil_service10_rating = db.Column(db.String(50))
    civil_service10_date = db.Column(db.String(50))
    civil_service10_place = db.Column(db.String(500))
    civil_service10_license_number = db.Column(db.String(100))
    civil_service10_license_valid_until = db.Column(db.String(50))
    
    # Section V: Work Experience (up to 20 entries)
    work_exp1_from_date = db.Column(db.String(50))
    work_exp1_to_date = db.Column(db.String(50))
    work_exp1_position_title = db.Column(db.String(500))
    work_exp1_department = db.Column(db.String(500))
    work_exp1_status_of_appointment = db.Column(db.String(200))
    work_exp1_govt_service = db.Column(db.String(10))  # Y or N
    work_exp1_description_of_duties = db.Column(db.Text)
    work_exp2_from_date = db.Column(db.String(50))
    work_exp2_to_date = db.Column(db.String(50))
    work_exp2_position_title = db.Column(db.String(500))
    work_exp2_department = db.Column(db.String(500))
    work_exp2_status_of_appointment = db.Column(db.String(200))
    work_exp2_govt_service = db.Column(db.String(10))
    work_exp2_description_of_duties = db.Column(db.Text)
    work_exp3_from_date = db.Column(db.String(50))
    work_exp3_to_date = db.Column(db.String(50))
    work_exp3_position_title = db.Column(db.String(500))
    work_exp3_department = db.Column(db.String(500))
    work_exp3_status_of_appointment = db.Column(db.String(200))
    work_exp3_govt_service = db.Column(db.String(10))
    work_exp3_description_of_duties = db.Column(db.Text)
    work_exp4_from_date = db.Column(db.String(50))
    work_exp4_to_date = db.Column(db.String(50))
    work_exp4_position_title = db.Column(db.String(500))
    work_exp4_department = db.Column(db.String(500))
    work_exp4_status_of_appointment = db.Column(db.String(200))
    work_exp4_govt_service = db.Column(db.String(10))
    work_exp4_description_of_duties = db.Column(db.Text)
    work_exp5_from_date = db.Column(db.String(50))
    work_exp5_to_date = db.Column(db.String(50))
    work_exp5_position_title = db.Column(db.String(500))
    work_exp5_department = db.Column(db.String(500))
    work_exp5_status_of_appointment = db.Column(db.String(200))
    work_exp5_govt_service = db.Column(db.String(10))
    work_exp5_description_of_duties = db.Column(db.Text)
    work_exp6_from_date = db.Column(db.String(50))
    work_exp6_to_date = db.Column(db.String(50))
    work_exp6_position_title = db.Column(db.String(500))
    work_exp6_department = db.Column(db.String(500))
    work_exp6_status_of_appointment = db.Column(db.String(200))
    work_exp6_govt_service = db.Column(db.String(10))
    work_exp6_description_of_duties = db.Column(db.Text)
    work_exp7_from_date = db.Column(db.String(50))
    work_exp7_to_date = db.Column(db.String(50))
    work_exp7_position_title = db.Column(db.String(500))
    work_exp7_department = db.Column(db.String(500))
    work_exp7_status_of_appointment = db.Column(db.String(200))
    work_exp7_govt_service = db.Column(db.String(10))
    work_exp7_description_of_duties = db.Column(db.Text)
    work_exp8_from_date = db.Column(db.String(50))
    work_exp8_to_date = db.Column(db.String(50))
    work_exp8_position_title = db.Column(db.String(500))
    work_exp8_department = db.Column(db.String(500))
    work_exp8_status_of_appointment = db.Column(db.String(200))
    work_exp8_govt_service = db.Column(db.String(10))
    work_exp8_description_of_duties = db.Column(db.Text)
    work_exp9_from_date = db.Column(db.String(50))
    work_exp9_to_date = db.Column(db.String(50))
    work_exp9_position_title = db.Column(db.String(500))
    work_exp9_department = db.Column(db.String(500))
    work_exp9_status_of_appointment = db.Column(db.String(200))
    work_exp9_govt_service = db.Column(db.String(10))
    work_exp9_description_of_duties = db.Column(db.Text)
    work_exp10_from_date = db.Column(db.String(50))
    work_exp10_to_date = db.Column(db.String(50))
    work_exp10_position_title = db.Column(db.String(500))
    work_exp10_department = db.Column(db.String(500))
    work_exp10_status_of_appointment = db.Column(db.String(200))
    work_exp10_govt_service = db.Column(db.String(10))
    work_exp10_description_of_duties = db.Column(db.Text)
    work_exp11_from_date = db.Column(db.String(50))
    work_exp11_to_date = db.Column(db.String(50))
    work_exp11_position_title = db.Column(db.String(500))
    work_exp11_department = db.Column(db.String(500))
    work_exp11_status_of_appointment = db.Column(db.String(200))
    work_exp11_govt_service = db.Column(db.String(10))
    work_exp11_description_of_duties = db.Column(db.Text)
    work_exp12_from_date = db.Column(db.String(50))
    work_exp12_to_date = db.Column(db.String(50))
    work_exp12_position_title = db.Column(db.String(500))
    work_exp12_department = db.Column(db.String(500))
    work_exp12_status_of_appointment = db.Column(db.String(200))
    work_exp12_govt_service = db.Column(db.String(10))
    work_exp12_description_of_duties = db.Column(db.Text)
    work_exp13_from_date = db.Column(db.String(50))
    work_exp13_to_date = db.Column(db.String(50))
    work_exp13_position_title = db.Column(db.String(500))
    work_exp13_department = db.Column(db.String(500))
    work_exp13_status_of_appointment = db.Column(db.String(200))
    work_exp13_govt_service = db.Column(db.String(10))
    work_exp13_description_of_duties = db.Column(db.Text)
    work_exp14_from_date = db.Column(db.String(50))
    work_exp14_to_date = db.Column(db.String(50))
    work_exp14_position_title = db.Column(db.String(500))
    work_exp14_department = db.Column(db.String(500))
    work_exp14_status_of_appointment = db.Column(db.String(200))
    work_exp14_govt_service = db.Column(db.String(10))
    work_exp14_description_of_duties = db.Column(db.Text)
    work_exp15_from_date = db.Column(db.String(50))
    work_exp15_to_date = db.Column(db.String(50))
    work_exp15_position_title = db.Column(db.String(500))
    work_exp15_department = db.Column(db.String(500))
    work_exp15_status_of_appointment = db.Column(db.String(200))
    work_exp15_govt_service = db.Column(db.String(10))
    work_exp15_description_of_duties = db.Column(db.Text)
    work_exp16_from_date = db.Column(db.String(50))
    work_exp16_to_date = db.Column(db.String(50))
    work_exp16_position_title = db.Column(db.String(500))
    work_exp16_department = db.Column(db.String(500))
    work_exp16_status_of_appointment = db.Column(db.String(200))
    work_exp16_govt_service = db.Column(db.String(10))
    work_exp16_description_of_duties = db.Column(db.Text)
    work_exp17_from_date = db.Column(db.String(50))
    work_exp17_to_date = db.Column(db.String(50))
    work_exp17_position_title = db.Column(db.String(500))
    work_exp17_department = db.Column(db.String(500))
    work_exp17_status_of_appointment = db.Column(db.String(200))
    work_exp17_govt_service = db.Column(db.String(10))
    work_exp17_description_of_duties = db.Column(db.Text)
    work_exp18_from_date = db.Column(db.String(50))
    work_exp18_to_date = db.Column(db.String(50))
    work_exp18_position_title = db.Column(db.String(500))
    work_exp18_department = db.Column(db.String(500))
    work_exp18_status_of_appointment = db.Column(db.String(200))
    work_exp18_govt_service = db.Column(db.String(10))
    work_exp18_description_of_duties = db.Column(db.Text)
    work_exp19_from_date = db.Column(db.String(50))
    work_exp19_to_date = db.Column(db.String(50))
    work_exp19_position_title = db.Column(db.String(500))
    work_exp19_department = db.Column(db.String(500))
    work_exp19_status_of_appointment = db.Column(db.String(200))
    work_exp19_govt_service = db.Column(db.String(10))
    work_exp19_description_of_duties = db.Column(db.Text)
    work_exp20_from_date = db.Column(db.String(50))
    work_exp20_to_date = db.Column(db.String(50))
    work_exp20_position_title = db.Column(db.String(500))
    work_exp20_department = db.Column(db.String(500))
    work_exp20_status_of_appointment = db.Column(db.String(200))
    work_exp20_govt_service = db.Column(db.String(10))
    work_exp20_description_of_duties = db.Column(db.Text)
    
    # Section VI: Voluntary Work (up to 10 entries)
    voluntary1_organization = db.Column(db.String(500))
    voluntary1_from_date = db.Column(db.String(50))
    voluntary1_to_date = db.Column(db.String(50))
    voluntary1_number_of_hours = db.Column(db.String(50))
    voluntary1_position = db.Column(db.String(500))
    voluntary2_organization = db.Column(db.String(500))
    voluntary2_from_date = db.Column(db.String(50))
    voluntary2_to_date = db.Column(db.String(50))
    voluntary2_number_of_hours = db.Column(db.String(50))
    voluntary2_position = db.Column(db.String(500))
    voluntary3_organization = db.Column(db.String(500))
    voluntary3_from_date = db.Column(db.String(50))
    voluntary3_to_date = db.Column(db.String(50))
    voluntary3_number_of_hours = db.Column(db.String(50))
    voluntary3_position = db.Column(db.String(500))
    voluntary4_organization = db.Column(db.String(500))
    voluntary4_from_date = db.Column(db.String(50))
    voluntary4_to_date = db.Column(db.String(50))
    voluntary4_number_of_hours = db.Column(db.String(50))
    voluntary4_position = db.Column(db.String(500))
    voluntary5_organization = db.Column(db.String(500))
    voluntary5_from_date = db.Column(db.String(50))
    voluntary5_to_date = db.Column(db.String(50))
    voluntary5_number_of_hours = db.Column(db.String(50))
    voluntary5_position = db.Column(db.String(500))
    voluntary6_organization = db.Column(db.String(500))
    voluntary6_from_date = db.Column(db.String(50))
    voluntary6_to_date = db.Column(db.String(50))
    voluntary6_number_of_hours = db.Column(db.String(50))
    voluntary6_position = db.Column(db.String(500))
    voluntary7_organization = db.Column(db.String(500))
    voluntary7_from_date = db.Column(db.String(50))
    voluntary7_to_date = db.Column(db.String(50))
    voluntary7_number_of_hours = db.Column(db.String(50))
    voluntary7_position = db.Column(db.String(500))
    voluntary8_organization = db.Column(db.String(500))
    voluntary8_from_date = db.Column(db.String(50))
    voluntary8_to_date = db.Column(db.String(50))
    voluntary8_number_of_hours = db.Column(db.String(50))
    voluntary8_position = db.Column(db.String(500))
    voluntary9_organization = db.Column(db.String(500))
    voluntary9_from_date = db.Column(db.String(50))
    voluntary9_to_date = db.Column(db.String(50))
    voluntary9_number_of_hours = db.Column(db.String(50))
    voluntary9_position = db.Column(db.String(500))
    voluntary10_organization = db.Column(db.String(500))
    voluntary10_from_date = db.Column(db.String(50))
    voluntary10_to_date = db.Column(db.String(50))
    voluntary10_number_of_hours = db.Column(db.String(50))
    voluntary10_position = db.Column(db.String(500))
    
    # Section VII: Learning and Development (L&D) Interventions/Training Programs (up to 50 entries)
    # Using a loop to generate all 50 entries would be too long, so I'll add them explicitly
    # Each entry has: title, from_date, to_date, number_of_hours, type_of_ld, conducted_by
    ld1_title = db.Column(db.String(500))
    ld1_from_date = db.Column(db.String(50))
    ld1_to_date = db.Column(db.String(50))
    ld1_number_of_hours = db.Column(db.String(50))
    ld1_type_of_ld = db.Column(db.String(200))
    ld1_conducted_by = db.Column(db.String(500))
    ld2_title = db.Column(db.String(500))
    ld2_from_date = db.Column(db.String(50))
    ld2_to_date = db.Column(db.String(50))
    ld2_number_of_hours = db.Column(db.String(50))
    ld2_type_of_ld = db.Column(db.String(200))
    ld2_conducted_by = db.Column(db.String(500))
    ld3_title = db.Column(db.String(500))
    ld3_from_date = db.Column(db.String(50))
    ld3_to_date = db.Column(db.String(50))
    ld3_number_of_hours = db.Column(db.String(50))
    ld3_type_of_ld = db.Column(db.String(200))
    ld3_conducted_by = db.Column(db.String(500))
    ld4_title = db.Column(db.String(500))
    ld4_from_date = db.Column(db.String(50))
    ld4_to_date = db.Column(db.String(50))
    ld4_number_of_hours = db.Column(db.String(50))
    ld4_type_of_ld = db.Column(db.String(200))
    ld4_conducted_by = db.Column(db.String(500))
    ld5_title = db.Column(db.String(500))
    ld5_from_date = db.Column(db.String(50))
    ld5_to_date = db.Column(db.String(50))
    ld5_number_of_hours = db.Column(db.String(50))
    ld5_type_of_ld = db.Column(db.String(200))
    ld5_conducted_by = db.Column(db.String(500))
    ld6_title = db.Column(db.String(500))
    ld6_from_date = db.Column(db.String(50))
    ld6_to_date = db.Column(db.String(50))
    ld6_number_of_hours = db.Column(db.String(50))
    ld6_type_of_ld = db.Column(db.String(200))
    ld6_conducted_by = db.Column(db.String(500))
    ld7_title = db.Column(db.String(500))
    ld7_from_date = db.Column(db.String(50))
    ld7_to_date = db.Column(db.String(50))
    ld7_number_of_hours = db.Column(db.String(50))
    ld7_type_of_ld = db.Column(db.String(200))
    ld7_conducted_by = db.Column(db.String(500))
    ld8_title = db.Column(db.String(500))
    ld8_from_date = db.Column(db.String(50))
    ld8_to_date = db.Column(db.String(50))
    ld8_number_of_hours = db.Column(db.String(50))
    ld8_type_of_ld = db.Column(db.String(200))
    ld8_conducted_by = db.Column(db.String(500))
    ld9_title = db.Column(db.String(500))
    ld9_from_date = db.Column(db.String(50))
    ld9_to_date = db.Column(db.String(50))
    ld9_number_of_hours = db.Column(db.String(50))
    ld9_type_of_ld = db.Column(db.String(200))
    ld9_conducted_by = db.Column(db.String(500))
    ld10_title = db.Column(db.String(500))
    ld10_from_date = db.Column(db.String(50))
    ld10_to_date = db.Column(db.String(50))
    ld10_number_of_hours = db.Column(db.String(50))
    ld10_type_of_ld = db.Column(db.String(200))
    ld10_conducted_by = db.Column(db.String(500))
    ld11_title = db.Column(db.String(500))
    ld11_from_date = db.Column(db.String(50))
    ld11_to_date = db.Column(db.String(50))
    ld11_number_of_hours = db.Column(db.String(50))
    ld11_type_of_ld = db.Column(db.String(200))
    ld11_conducted_by = db.Column(db.String(500))
    ld12_title = db.Column(db.String(500))
    ld12_from_date = db.Column(db.String(50))
    ld12_to_date = db.Column(db.String(50))
    ld12_number_of_hours = db.Column(db.String(50))
    ld12_type_of_ld = db.Column(db.String(200))
    ld12_conducted_by = db.Column(db.String(500))
    ld13_title = db.Column(db.String(500))
    ld13_from_date = db.Column(db.String(50))
    ld13_to_date = db.Column(db.String(50))
    ld13_number_of_hours = db.Column(db.String(50))
    ld13_type_of_ld = db.Column(db.String(200))
    ld13_conducted_by = db.Column(db.String(500))
    ld14_title = db.Column(db.String(500))
    ld14_from_date = db.Column(db.String(50))
    ld14_to_date = db.Column(db.String(50))
    ld14_number_of_hours = db.Column(db.String(50))
    ld14_type_of_ld = db.Column(db.String(200))
    ld14_conducted_by = db.Column(db.String(500))
    ld15_title = db.Column(db.String(500))
    ld15_from_date = db.Column(db.String(50))
    ld15_to_date = db.Column(db.String(50))
    ld15_number_of_hours = db.Column(db.String(50))
    ld15_type_of_ld = db.Column(db.String(200))
    ld15_conducted_by = db.Column(db.String(500))
    ld16_title = db.Column(db.String(500))
    ld16_from_date = db.Column(db.String(50))
    ld16_to_date = db.Column(db.String(50))
    ld16_number_of_hours = db.Column(db.String(50))
    ld16_type_of_ld = db.Column(db.String(200))
    ld16_conducted_by = db.Column(db.String(500))
    ld17_title = db.Column(db.String(500))
    ld17_from_date = db.Column(db.String(50))
    ld17_to_date = db.Column(db.String(50))
    ld17_number_of_hours = db.Column(db.String(50))
    ld17_type_of_ld = db.Column(db.String(200))
    ld17_conducted_by = db.Column(db.String(500))
    ld18_title = db.Column(db.String(500))
    ld18_from_date = db.Column(db.String(50))
    ld18_to_date = db.Column(db.String(50))
    ld18_number_of_hours = db.Column(db.String(50))
    ld18_type_of_ld = db.Column(db.String(200))
    ld18_conducted_by = db.Column(db.String(500))
    ld19_title = db.Column(db.String(500))
    ld19_from_date = db.Column(db.String(50))
    ld19_to_date = db.Column(db.String(50))
    ld19_number_of_hours = db.Column(db.String(50))
    ld19_type_of_ld = db.Column(db.String(200))
    ld19_conducted_by = db.Column(db.String(500))
    ld20_title = db.Column(db.String(500))
    ld20_from_date = db.Column(db.String(50))
    ld20_to_date = db.Column(db.String(50))
    ld20_number_of_hours = db.Column(db.String(50))
    ld20_type_of_ld = db.Column(db.String(200))
    ld20_conducted_by = db.Column(db.String(500))
    ld21_title = db.Column(db.String(500))
    ld21_from_date = db.Column(db.String(50))
    ld21_to_date = db.Column(db.String(50))
    ld21_number_of_hours = db.Column(db.String(50))
    ld21_type_of_ld = db.Column(db.String(200))
    ld21_conducted_by = db.Column(db.String(500))
    ld22_title = db.Column(db.String(500))
    ld22_from_date = db.Column(db.String(50))
    ld22_to_date = db.Column(db.String(50))
    ld22_number_of_hours = db.Column(db.String(50))
    ld22_type_of_ld = db.Column(db.String(200))
    ld22_conducted_by = db.Column(db.String(500))
    ld23_title = db.Column(db.String(500))
    ld23_from_date = db.Column(db.String(50))
    ld23_to_date = db.Column(db.String(50))
    ld23_number_of_hours = db.Column(db.String(50))
    ld23_type_of_ld = db.Column(db.String(200))
    ld23_conducted_by = db.Column(db.String(500))
    ld24_title = db.Column(db.String(500))
    ld24_from_date = db.Column(db.String(50))
    ld24_to_date = db.Column(db.String(50))
    ld24_number_of_hours = db.Column(db.String(50))
    ld24_type_of_ld = db.Column(db.String(200))
    ld24_conducted_by = db.Column(db.String(500))
    ld25_title = db.Column(db.String(500))
    ld25_from_date = db.Column(db.String(50))
    ld25_to_date = db.Column(db.String(50))
    ld25_number_of_hours = db.Column(db.String(50))
    ld25_type_of_ld = db.Column(db.String(200))
    ld25_conducted_by = db.Column(db.String(500))
    ld26_title = db.Column(db.String(500))
    ld26_from_date = db.Column(db.String(50))
    ld26_to_date = db.Column(db.String(50))
    ld26_number_of_hours = db.Column(db.String(50))
    ld26_type_of_ld = db.Column(db.String(200))
    ld26_conducted_by = db.Column(db.String(500))
    ld27_title = db.Column(db.String(500))
    ld27_from_date = db.Column(db.String(50))
    ld27_to_date = db.Column(db.String(50))
    ld27_number_of_hours = db.Column(db.String(50))
    ld27_type_of_ld = db.Column(db.String(200))
    ld27_conducted_by = db.Column(db.String(500))
    ld28_title = db.Column(db.String(500))
    ld28_from_date = db.Column(db.String(50))
    ld28_to_date = db.Column(db.String(50))
    ld28_number_of_hours = db.Column(db.String(50))
    ld28_type_of_ld = db.Column(db.String(200))
    ld28_conducted_by = db.Column(db.String(500))
    ld29_title = db.Column(db.String(500))
    ld29_from_date = db.Column(db.String(50))
    ld29_to_date = db.Column(db.String(50))
    ld29_number_of_hours = db.Column(db.String(50))
    ld29_type_of_ld = db.Column(db.String(200))
    ld29_conducted_by = db.Column(db.String(500))
    ld30_title = db.Column(db.String(500))
    ld30_from_date = db.Column(db.String(50))
    ld30_to_date = db.Column(db.String(50))
    ld30_number_of_hours = db.Column(db.String(50))
    ld30_type_of_ld = db.Column(db.String(200))
    ld30_conducted_by = db.Column(db.String(500))
    ld31_title = db.Column(db.String(500))
    ld31_from_date = db.Column(db.String(50))
    ld31_to_date = db.Column(db.String(50))
    ld31_number_of_hours = db.Column(db.String(50))
    ld31_type_of_ld = db.Column(db.String(200))
    ld31_conducted_by = db.Column(db.String(500))
    ld32_title = db.Column(db.String(500))
    ld32_from_date = db.Column(db.String(50))
    ld32_to_date = db.Column(db.String(50))
    ld32_number_of_hours = db.Column(db.String(50))
    ld32_type_of_ld = db.Column(db.String(200))
    ld32_conducted_by = db.Column(db.String(500))
    ld33_title = db.Column(db.String(500))
    ld33_from_date = db.Column(db.String(50))
    ld33_to_date = db.Column(db.String(50))
    ld33_number_of_hours = db.Column(db.String(50))
    ld33_type_of_ld = db.Column(db.String(200))
    ld33_conducted_by = db.Column(db.String(500))
    ld34_title = db.Column(db.String(500))
    ld34_from_date = db.Column(db.String(50))
    ld34_to_date = db.Column(db.String(50))
    ld34_number_of_hours = db.Column(db.String(50))
    ld34_type_of_ld = db.Column(db.String(200))
    ld34_conducted_by = db.Column(db.String(500))
    ld35_title = db.Column(db.String(500))
    ld35_from_date = db.Column(db.String(50))
    ld35_to_date = db.Column(db.String(50))
    ld35_number_of_hours = db.Column(db.String(50))
    ld35_type_of_ld = db.Column(db.String(200))
    ld35_conducted_by = db.Column(db.String(500))
    ld36_title = db.Column(db.String(500))
    ld36_from_date = db.Column(db.String(50))
    ld36_to_date = db.Column(db.String(50))
    ld36_number_of_hours = db.Column(db.String(50))
    ld36_type_of_ld = db.Column(db.String(200))
    ld36_conducted_by = db.Column(db.String(500))
    ld37_title = db.Column(db.String(500))
    ld37_from_date = db.Column(db.String(50))
    ld37_to_date = db.Column(db.String(50))
    ld37_number_of_hours = db.Column(db.String(50))
    ld37_type_of_ld = db.Column(db.String(200))
    ld37_conducted_by = db.Column(db.String(500))
    ld38_title = db.Column(db.String(500))
    ld38_from_date = db.Column(db.String(50))
    ld38_to_date = db.Column(db.String(50))
    ld38_number_of_hours = db.Column(db.String(50))
    ld38_type_of_ld = db.Column(db.String(200))
    ld38_conducted_by = db.Column(db.String(500))
    ld39_title = db.Column(db.String(500))
    ld39_from_date = db.Column(db.String(50))
    ld39_to_date = db.Column(db.String(50))
    ld39_number_of_hours = db.Column(db.String(50))
    ld39_type_of_ld = db.Column(db.String(200))
    ld39_conducted_by = db.Column(db.String(500))
    ld40_title = db.Column(db.String(500))
    ld40_from_date = db.Column(db.String(50))
    ld40_to_date = db.Column(db.String(50))
    ld40_number_of_hours = db.Column(db.String(50))
    ld40_type_of_ld = db.Column(db.String(200))
    ld40_conducted_by = db.Column(db.String(500))
    ld41_title = db.Column(db.String(500))
    ld41_from_date = db.Column(db.String(50))
    ld41_to_date = db.Column(db.String(50))
    ld41_number_of_hours = db.Column(db.String(50))
    ld41_type_of_ld = db.Column(db.String(200))
    ld41_conducted_by = db.Column(db.String(500))
    ld42_title = db.Column(db.String(500))
    ld42_from_date = db.Column(db.String(50))
    ld42_to_date = db.Column(db.String(50))
    ld42_number_of_hours = db.Column(db.String(50))
    ld42_type_of_ld = db.Column(db.String(200))
    ld42_conducted_by = db.Column(db.String(500))
    ld43_title = db.Column(db.String(500))
    ld43_from_date = db.Column(db.String(50))
    ld43_to_date = db.Column(db.String(50))
    ld43_number_of_hours = db.Column(db.String(50))
    ld43_type_of_ld = db.Column(db.String(200))
    ld43_conducted_by = db.Column(db.String(500))
    ld44_title = db.Column(db.String(500))
    ld44_from_date = db.Column(db.String(50))
    ld44_to_date = db.Column(db.String(50))
    ld44_number_of_hours = db.Column(db.String(50))
    ld44_type_of_ld = db.Column(db.String(200))
    ld44_conducted_by = db.Column(db.String(500))
    ld45_title = db.Column(db.String(500))
    ld45_from_date = db.Column(db.String(50))
    ld45_to_date = db.Column(db.String(50))
    ld45_number_of_hours = db.Column(db.String(50))
    ld45_type_of_ld = db.Column(db.String(200))
    ld45_conducted_by = db.Column(db.String(500))
    ld46_title = db.Column(db.String(500))
    ld46_from_date = db.Column(db.String(50))
    ld46_to_date = db.Column(db.String(50))
    ld46_number_of_hours = db.Column(db.String(50))
    ld46_type_of_ld = db.Column(db.String(200))
    ld46_conducted_by = db.Column(db.String(500))
    ld47_title = db.Column(db.String(500))
    ld47_from_date = db.Column(db.String(50))
    ld47_to_date = db.Column(db.String(50))
    ld47_number_of_hours = db.Column(db.String(50))
    ld47_type_of_ld = db.Column(db.String(200))
    ld47_conducted_by = db.Column(db.String(500))
    ld48_title = db.Column(db.String(500))
    ld48_from_date = db.Column(db.String(50))
    ld48_to_date = db.Column(db.String(50))
    ld48_number_of_hours = db.Column(db.String(50))
    ld48_type_of_ld = db.Column(db.String(200))
    ld48_conducted_by = db.Column(db.String(500))
    ld49_title = db.Column(db.String(500))
    ld49_from_date = db.Column(db.String(50))
    ld49_to_date = db.Column(db.String(50))
    ld49_number_of_hours = db.Column(db.String(50))
    ld49_type_of_ld = db.Column(db.String(200))
    ld49_conducted_by = db.Column(db.String(500))
    ld50_title = db.Column(db.String(500))
    ld50_from_date = db.Column(db.String(50))
    ld50_to_date = db.Column(db.String(50))
    ld50_number_of_hours = db.Column(db.String(50))
    ld50_type_of_ld = db.Column(db.String(200))
    ld50_conducted_by = db.Column(db.String(500))
    
    # Section VIII: Other Information - Special Skills and Hobbies (up to 15 entries)
    special_skill1 = db.Column(db.String(500))
    special_skill2 = db.Column(db.String(500))
    special_skill3 = db.Column(db.String(500))
    special_skill4 = db.Column(db.String(500))
    special_skill5 = db.Column(db.String(500))
    special_skill6 = db.Column(db.String(500))
    special_skill7 = db.Column(db.String(500))
    special_skill8 = db.Column(db.String(500))
    special_skill9 = db.Column(db.String(500))
    special_skill10 = db.Column(db.String(500))
    special_skill11 = db.Column(db.String(500))
    special_skill12 = db.Column(db.String(500))
    special_skill13 = db.Column(db.String(500))
    special_skill14 = db.Column(db.String(500))
    special_skill15 = db.Column(db.String(500))
    
    # Section VIII: Other Information - Non-Academic Distinctions/Recognition (up to 15 entries)
    non_academic1 = db.Column(db.String(500))
    non_academic2 = db.Column(db.String(500))
    non_academic3 = db.Column(db.String(500))
    non_academic4 = db.Column(db.String(500))
    non_academic5 = db.Column(db.String(500))
    non_academic6 = db.Column(db.String(500))
    non_academic7 = db.Column(db.String(500))
    non_academic8 = db.Column(db.String(500))
    non_academic9 = db.Column(db.String(500))
    non_academic10 = db.Column(db.String(500))
    non_academic11 = db.Column(db.String(500))
    non_academic12 = db.Column(db.String(500))
    non_academic13 = db.Column(db.String(500))
    non_academic14 = db.Column(db.String(500))
    non_academic15 = db.Column(db.String(500))
    
    # Section VIII: Other Information - Membership in Association/Organization (up to 15 entries)
    membership1 = db.Column(db.String(500))
    membership2 = db.Column(db.String(500))
    membership3 = db.Column(db.String(500))
    membership4 = db.Column(db.String(500))
    membership5 = db.Column(db.String(500))
    membership6 = db.Column(db.String(500))
    membership7 = db.Column(db.String(500))
    membership8 = db.Column(db.String(500))
    membership9 = db.Column(db.String(500))
    membership10 = db.Column(db.String(500))
    membership11 = db.Column(db.String(500))
    membership12 = db.Column(db.String(500))
    membership13 = db.Column(db.String(500))
    membership14 = db.Column(db.String(500))
    membership15 = db.Column(db.String(500))
    
    # Section VIII: Other Information - Items 34-37
    # Item 34: Related by consanguinity or affinity
    related_third_degree = db.Column(db.Boolean, default=False)
    related_fourth_degree = db.Column(db.Boolean, default=False)
    related_details = db.Column(db.Text)
    
    # Item 35: Administrative offense and criminal charges
    admin_offense_guilty = db.Column(db.Boolean, default=False)
    admin_offense_details = db.Column(db.Text)
    criminally_charged = db.Column(db.Boolean, default=False)
    criminal_charge_details = db.Column(db.Text)
    criminal_charge_date_filed = db.Column(db.String(50))
    criminal_charge_status = db.Column(db.String(500))
    
    # Item 36: Convicted of any crime
    convicted_crime = db.Column(db.Boolean, default=False)
    convicted_crime_details = db.Column(db.Text)
    
    # Item 37: Separated from service
    separated_from_service = db.Column(db.Boolean, default=False)
    separated_from_service_details = db.Column(db.Text)
    
    # Section VIII: Other Information - Items 38-40
    # Item 38: Political involvement
    candidate_in_election = db.Column(db.Boolean, default=False)
    candidate_in_election_details = db.Column(db.Text)
    resigned_for_election = db.Column(db.Boolean, default=False)
    resigned_for_election_details = db.Column(db.Text)
    
    # Item 39: Immigration status
    immigrant_permanent_resident = db.Column(db.Boolean, default=False)
    immigrant_country = db.Column(db.String(200))
    
    # Item 40: Special groups
    indigenous_group_member = db.Column(db.Boolean, default=False)
    indigenous_group_specify = db.Column(db.String(500))
    person_with_disability = db.Column(db.Boolean, default=False)
    disability_id_no = db.Column(db.String(200))
    solo_parent = db.Column(db.Boolean, default=False)
    solo_parent_id_no = db.Column(db.String(200))
    
    # Section VIII: Other Information - Items 41-42
    # Item 41: References (3 references)
    reference1_name = db.Column(db.String(500))
    reference1_address = db.Column(db.Text)
    reference1_contact = db.Column(db.String(500))
    reference2_name = db.Column(db.String(500))
    reference2_address = db.Column(db.Text)
    reference2_contact = db.Column(db.String(500))
    reference3_name = db.Column(db.String(500))
    reference3_address = db.Column(db.Text)
    reference3_contact = db.Column(db.String(500))
    
    # Item 42: Declaration (no fields needed, just text)
    
    # Government Issued ID (below Item 42)
    government_issued_id = db.Column(db.String(500))
    id_license_passport_no = db.Column(db.String(200))
    date_place_of_issuance = db.Column(db.String(500))
    
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationship
    employee = db.relationship('Employee', backref='pds', uselist=False)
    
    def __repr__(self):
        return f'<EmployeePDS {self.employee_id}>'
